Rename non-getter `getX` methods
EasyPost/easypost-java pull request #149
Opened 2022-06-21 18:45 UTC by nwithan8

# Description

To avoid confusion between proper getter/setter functions and other functions that merely start with the word `get`, all non-getter `getX` functions have been renamed to simply `X` (i.e. `getLowestSmartrate()` -> `lowestSmartrate()`).

This will avoid unnecessary exception throwing and catching during object merges, which utilizes getter/setter pairs and gets confused when there is no `setX` for a given `getX` function.

# Testing

All tests pass as expected.

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2022-06-21 18:57 UTC, Justintime50 requested changes
The goal is not to make a breaking change here but to keep the original functions present but deprecate them and point users to the new (correctly named) items. Then when we have a major release, we can remove the deprecated items and the odd workaround.

2022-06-21 18:57 UTC, Justintime50 commented on src/main/java/com/easypost/model/CarrierAccount.java
> +    public boolean isClone() {
Shouldn't this be `get` in a perfect world?

2022-06-22 15:36 UTC, Justintime50 submitted a review, later dismissed
There's a ton of changes not related at all to the smartrate deprecation. Please remove or pull unrelated refactoring out into a separate PR. This PR should really only touch 2 files.

2022-06-22 20:40 UTC, Justintime50 commented on CHANGELOG.md
> +    - `getSmartRateAccuracy()` -> `smartrateAccuracy()`
This line needs to be removed since it's a getter and not getting removed.

2022-06-22 20:57 UTC, Justintime50 approved these changes

2022-06-24 17:26 UTC, jchen293 approved these changes

2022-06-24 17:51 UTC, merged