Security analysis and Makefile
EasyPost/easypost-java pull request #156
Opened 2022-07-06 19:52 UTC by nwithan8

# Description

- Add dependency-check as dependency
- Add Makefile for common commands (lint, security check, build, release, publish, etc)
- Add CI step (see notes)

# Testing

- All Makefile commands work as expected
- Dependency check runs from command line as expected
- All unit tests pass as expected, no changes or re-recording needed

# Notes
- The dependency check generates an HTML report after running, which is then uploaded as an artifact (example below). The CI step itself should fail on severe CVSs (plugin is configured to fail a build if there are any CVSs with a score 7+)
- There is also a [free GitHub integration](https://github.com/marketplace/muse-dev/plan/MLP_kgDNGN8) from Sonatype (who run the Maven repository) to scan for CVSs, that we might want to consider. This should be in addition to the CI tool, not as a replacement, to allow local CVS scanning still
- Example report: <img width="1348" alt="image" src="https://user-images.githubusercontent.com/17054780/177659474-297c49ad-1679-47fd-9e87-4d202f5eed9d.png">

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2022-07-06 20:35 UTC, Justintime50 requested changes
If this tool isn't capable of throwing errors then we should investigate it's usage more or use another tool as a manual tool is counterproductive. 

Additionally, I know this library has security issues (as I remember your IDE getting upset at us some months ago), certainly it should be complaining and there should be some fixes required here (bumping patch versions of deps and whatnot). Can we investigate this a bit more?

2022-07-06 23:06 UTC, nwithan8 commented
> If this tool isn't capable of throwing errors then we should investigate it's usage more or use another tool as a manual tool is counterproductive.
> 
> Additionally, I know this library has security issues (as I remember your IDE getting upset at us some months ago), certainly it should be complaining and there should be some fixes required here (bumping patch versions of deps and whatnot). Can we investigate this a bit more?

After running Dependency Check a half-dozen different ways with various strict configurations, it has not detected any vulnerabilites.

I know in the past (and still currently), my IntelliJ IDE's Maven tool is reporting that `EasyVCR` is transitively vulnerable to some low-threat CVEs, but Sonatype themselves [do not report any vulnerabilities](https://ossindex.sonatype.org/component/pkg:maven/com.easypost/easyvcr@0.3.0?utm_source=dependency-check&utm_medium=integration&utm_content=7.1.1) with `EasyVCR`, leading me to believe my IDE is wrong.

FWIW, the IDE vulnerability checks are powered by [Checkmarx](https://checkmarx.com/), which is a paid product.

2022-07-06 23:13 UTC, nwithan8 commented on pom.xml
> +            <groupId>org.jetbrains</groupId>
This is a dependency for DependencyCheck.

2022-07-07 06:02 UTC, Justintime50 approved these changes

2022-07-07 16:27 UTC, jchen293 approved these changes

2022-07-07 16:28 UTC, merged