convert return type for fundWallet and deletePaymentMethod
EasyPost/easypost-java pull request #190
Opened 2022-09-30 18:58 UTC by jchen293

# Description

convert return type for `fundWallet()` and `deletePaymentMethod()`

# Testing

Unit tests pass

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2022-09-30 19:49 UTC, nwithan8 submitted a review, later dismissed

2022-09-30 20:17 UTC, Justintime50 requested changes
`updateEmail` and `createList` needs these changes too.

2022-10-03 16:24 UTC, Justintime50 approved these changes

2022-10-03 17:19 UTC, nwithan8 approved these changes

2022-10-03 17:20 UTC, merged