fix warnings from error prone
EasyPost/easypost-java pull request #270
Opened 2023-05-30 21:20 UTC by jchen293

# Description

Fixed the warnings that were thrown from Error Prone and VS code.
Added missing docstrings
Removed the deprecated functions in unit tests

# Testing

![Screenshot 2023-05-30 at 5 20 14 PM](https://github.com/EasyPost/easypost-java/assets/22759143/711dc9b8-2369-4dd1-a225-0ee3686296a8)

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2023-05-30 21:56 UTC, nwithan8 requested changes

2023-05-30 21:56 UTC, nwithan8 commented on src/test/java/com/easypost/AddressTest.java
> -        assertTrue(addressesList.stream().allMatch(address -> address instanceof Address));
Can you explain why this change was made?

2023-05-31 15:51 UTC, Justintime50 commented on src/test/java/com/easypost/BatchTest.java
> +        assertTrue(batchesList.stream().allMatch(batch -> batch != null));
question: can you help me understand why we are changing these assertions? This is a much weaker assertion. The whole point of checking instance of is to ensure that we are deserializinig objects correctly.

2023-05-31 17:00 UTC, Justintime50 approved these changes

2023-05-31 17:02 UTC, nwithan8 approved these changes

2023-05-31 17:08 UTC, merged