Add new updateUps function for UPS account update in CarrierAccountSe…
EasyPost/easypost-java pull request #317
Opened 2024-07-08 18:35 UTC by jchen293

…rvice

# Description

- Adds new `updateUps` function under `CarrierAccountService`
  - Starting `2024-08-05`, UPS accounts can no longer be updated through the normal update function and must use the UPS specific `updateUps` function
# Testing

Add unit tests to make sure we are hitting the correct endpoints.

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2024-07-08 21:09 UTC, nwithan8 requested changes

2024-07-08 21:09 UTC, nwithan8 commented on src/main/java/com/easypost/service/CarrierAccountService.java
> +        } else if (type.equals("UpsAccount")) {
Need to account for "UpsMailInnovationsAccount" and 
"UpsSurepostAccount" as well

2024-07-08 21:09 UTC, nwithan8 commented on src/main/java/com/easypost/service/CarrierAccountService.java
> +        } else if (carrierAccountType.equals("UpsAccount")) {
Need to account for "UpsMailInnovationsAccount" and
"UpsSurepostAccount" as well

2024-07-09 20:45 UTC, nwithan8 submitted a review, later dismissed

2024-07-10 21:19 UTC, Justintime50 approved these changes

2024-07-10 21:24 UTC, jchen293 commented on src/test/java/com/easypost/CarrierAccountTest.java
> +     * Test creating a carrier account with a custom workflow.
Going to fix this in the next SmartRate PR, so I don't dismiss the approval again

2024-07-10 21:24 UTC, merged