feat: adds surcharges property and model to Rate object
EasyPost/easypost-java pull request #328
Opened 2024-08-07 15:46 UTC by Justintime50

# Description

# Testing

# Pull Request Type

Please select the option(s) that are relevant to this PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement (fixing a typo, updating readme, renaming a variable name, etc)

2024-08-07 15:51 UTC, jchen293 requested changes

2024-08-07 15:51 UTC, jchen293 commented on src/main/java/com/easypost/model/Surcharge.java
> +    private String retail_amount;
these should be camel case in java

2024-09-30 19:06 UTC, Justintime50 commented
Going to close until needed

2024-09-30 19:06 UTC, closed without merging

2026-09-30 21:52 UTC, AlexanderIskander commented
Hey, is there any plans to add this feature? Thanks

2026-09-30 21:54 UTC, Justintime50 commented
> Hey, is there any plans to add this feature? Thanks

I'll check with our internal teams on where this ended up

2026-10-01 15:34 UTC, Justintime50 commented
Looks like this was indeed implemented (available by talking to our support team if you don't have it enabled already)

I will get this implemented across our suite of libs shortly.

2026-10-01 16:51 UTC, stephenjwatkins approved these changes

2026-10-01 16:55 UTC, Justintime50 commented
@AlexanderIskander this will go live probably next week (we have some additional pending changes we may pair with this next release), keep an eye out! Thanks for bringing it up.

2026-10-01 16:58 UTC, AlexanderIskander commented
Thanks! Appreciate the quick fix.