Add createFedEx() method to register FedEx accounts via API
EasyPost/easypost-java pull request #50
Opened 2020-03-11 17:54 UTC by roehnan

People have requested that FedEx account registration via API be added to the client library.

Here is an example of how it works:

```
import java.util.HashMap;
import java.util.Map;
import java.util.List;
import java.util.ArrayList;

import com.easypost.EasyPost;
import com.easypost.exception.EasyPostException;
import com.easypost.model.CarrierAccount;

public class FedExTest {

    public static void main(String[] args) {
        EasyPost.apiKey = System.getenv("epProd");

        Map<String, Object> accountParams = new HashMap<String, Object>();
        
        accountParams.put("account_number", "ACCOUNT_NUMBER");
        accountParams.put("corporate_first_name", "CORPORATE_FIRST_NAME");
        accountParams.put("corporate_last_name", "CORPORATE_LAST_NAME");
        accountParams.put("corporate_company_name", "CORPORATE_COMPANY_NAME");
        accountParams.put("corporate_phone_number", "CORPORATE_PHONE_NUMBER");
        accountParams.put("corporate_email_address", "CORPORATE_EMAIL_ADDRESS");
        accountParams.put("corporate_streets", "CORPORATE_STREETS");
        accountParams.put("corporate_city", "CORPORATE_CITY");
        accountParams.put("corporate_state", "CORPORATE_STATE");
        accountParams.put("corporate_postal_code", "CORPORATE_POSTAL_CODE");
        accountParams.put("corporate_country_code", "CORPORATE_COUNTRY_CODE");
        accountParams.put("corporate_job_title", "CORPORATE_JOB_TITLE");
        accountParams.put("shipping_streets", "SHIPPING_STREETS");
        accountParams.put("shipping_city", "SHIPPING_CITY");
        accountParams.put("shipping_state", "SHIPPING_STATE");
        accountParams.put("shipping_postal_code", "SHIPPING_POSTAL_CODE");
        accountParams.put("shipping_country_code", "SHIPPING_COUNTRY_CODE");

        try {
            CarrierAccount ca = CarrierAccount.createFedEx(accountParams);
            System.out.println(ca.prettyPrint());

        } catch (EasyPostException e) {
            e.printStackTrace();
        }
    }
}
```

2020-03-12 14:49 UTC, roehnan commented
The Travis CI build is failing due to the pom.xml configuration... I received the same error when I tried to run maven manually.

I needed to update lines 108-121:
```            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.9.1</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
to 

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.9.1</version>
                <configuration>
                    <source>8</source>
                </configuration>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

2020-06-11 20:49 UTC, att14 commented on src/main/java/com/easypost/model/CarrierAccount.java
> +		public static CarrierAccount createFedEx(Map<String, Object> params, String apiKey) throws EasyPostException {
We should call this `register` not `create` since that's what we call the API.

2020-06-11 20:50 UTC, att14 commented on src/main/java/com/easypost/model/CarrierAccount.java
> +			return request(RequestMethod.POST, String.format("%s/%s", EasyPost.API_BASE, "fedex_registrations"), wrappedParams, CarrierAccount.class, apiKey);
We should be using `carrier_accounts/register` instead of `fedex_registrations`.

2021-06-28 20:49 UTC, Justintime50 requested changes
We'll want to implement this in a more generic way so that accounts such as FedEx and UPS can both be added via a single method/interface if possible. We are working on a holistic approach across all our client libraries and as such, I'll close this for now.

2021-06-28 20:49 UTC, Justintime50 commented on src/main/java/com/easypost/model/Batch.java
> +		return request(RequestMethod.POST, String.format("%s/create_and_buy", classURL(Batch.class)), wrappedParams, Batch.class, apiKey);
We'll want to make bug fixes separate from feature releases in distinct PRs.

2021-06-28 20:49 UTC, closed without merging