Fixed hard code for support mail and removed print statement
EasyPost/easypost-java pull request #77
Opened 2021-12-10 21:31 UTC by jchen293

Added a variable for support mail and replaced it with hard-coded emails with the constant inline with the strings using it.
Removed print statement.

2021-12-10 22:06 UTC, Justintime50 requested changes

2021-12-10 22:06 UTC, Justintime50 commented on src/test/java/com/easypost/EasyPostTest.java
> -        */
Let's leave code alone that isn't part of the ask for the PR.

2021-12-10 22:06 UTC, Justintime50 commented on src/main/java/com/easypost/net/EasyPostResponse.java
> -    // System.out.println(this.responseBody);
This is already being removed from the JSON PR @nwithan8 is doing, you can leave it alone and it'll be take care of separately.

2021-12-10 22:06 UTC, Justintime50 commented on src/main/java/com/easypost/net/EasyPostResource.java
> -	// }
Let's leave code alone that isn't part of the ask for the PR.

2021-12-11 00:14 UTC, nwithan8 approved these changes
LGTM

2021-12-11 00:31 UTC, Justintime50 reviewed
Ah yes... string interpolation - one of many things Java doesn't have. Would we want to consider using `String.format()` instead to clean it up so we don't have to break up the strings?

2021-12-12 20:48 UTC, jchen293 commented
Used String.format() to clean up the print statement.

2021-12-13 17:58 UTC, Justintime50 requested changes
The rest looks good, one was missed.

2021-12-13 17:58 UTC, Justintime50 commented on src/main/java/com/easypost/model/EventDeserializer.java
> +					"Please email us at " + EasyPostResource.EASYPOST_SUPPORT_EMAIL + ".");
Looks like there was one missed to switch to `String.format()`

2021-12-13 18:31 UTC, Justintime50 approved these changes

2021-12-13 19:38 UTC, nwithan8 approved these changes

2021-12-13 19:38 UTC, merged